### PR TITLE
Fix a DB Constraint violation issue

### PR DESCRIPTION
**Pull request by seamuslee001**
This fixes a DB Constraint violation issue that was occurring for the Australian Greens. We patched this locally for us and have been working fine since October 2018

ping @agileware-fj

### CODE REVIEW

**Comment by agileware-fj** [comment]
@seamuslee001 Can you explain the constraint violation?  Was is producing duplicate email & phone ids?

Thanks

**Comment by agileware-fj** [comment]
Ah I see there's a code comment about that.

**Comment by agileware-fj** [comment]
Looks good, but I'll need to do some run tests on this before merging.  Thanks.

**Comment by agileware-justin** [comment]
This repo wasn't up to date, so I've pushed the latest history, which included a rename.
The PR doesn't apply anymore so I've just transferred over the change anyway.
Thanks and good night!

**Pull request closed without merging**
